import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    plugins: [
        laravel({
            input: ['resources/css/app.css',
            'resources/css/animate.css',
            'resources/css/animate.min.css',
            'resources/css/bootstrap-theme.css',
            'resources/css/bootstrap-theme.css.map',
            'resources/css/bootstrap-theme.min.css',
            'resources/css/bootstrap.css',
            'resources/css/bootstrap.css.map',
            'resources/css/bootstrap.min.css',
            'resources/css/buscador.css',
            'resources/css/demo.css',
            'resources/css/estilo.css',
            'resources/css/estilos2.css',
            'resources/css/font-awesome.css',
            'resources/css/font-awesome.min.css',
            'resources/css/isotope.css',
            'resources/css/jquery.bxslider.css',
            'resources/css/login.css',
            'resources/css/normalize.css',
            'resources/css/overwrite.css',
            'resources/css/pcarga.css',
            'resources/css/set1.css',
            'resources/css/set2.css',
            'resources/css/style.css',
            'resources/css/style404.css',
            'resources/css/tabla.css',

            'resources/js/bootstrap.js',
            'resources/js/bootstrap.min.js',
            'resources/js/fliplightbox.min.js',
            'resources/js/funcionalidad.js',
            'resources/js/funcionalidad2.js',
            'resources/js/funcionalidad3.js',
            'resources/js/functions.js',
            'resources/js/jquery-2.1.1.min.js',
            'resources/js/jquery.bxslider.min.js',
            'resources/js/jquery.easing.1.3.js',
            'resources/js/jquery.isotope.min.js',
            'resources/js/labels.js',
            'resources/js/wow.min.js',           
            'resources/js/app.js'],
            refresh: true,
        }),
    ],
});
